<a href="https://colab.research.google.com/github/Venchislav/Neural-Networks/blob/main/NewHorizon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I have already touched numpy. But it's just refreshment of my knowledge. And...
I work on course where numpy lesson is touched, so here it is💂‍♂️

In [ ]:
import numpy as np

In [ ]:
# 2d array
arr_dd = np.zeros((2, 3), dtype=np.float32)
arr_dd

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
# 3d arr
arr_ddd = np.zeros((2, 3, 4), dtype=np.float32)
arr_ddd

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

ARITHMETICS WITH MATRICES

In [ ]:
arr_ddd += 1

In [ ]:
arr_ddd

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [ ]:
arr_ddd *= 2

In [ ]:
arr_ddd

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]], dtype=float32)

In [ ]:
arr_ddd[0]

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)

In [ ]:
arr_ddd[0, 2]

array([2., 2., 2., 2.], dtype=float32)

In [ ]:
arr_ddd[0, 2, 3]

2.0

In [ ]:
o = np.ones((2, 3, 4, 5))

In [ ]:
o

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [ ]:
# we can make these arrays in easier and more elegant way

In [ ]:
ones = lambda *shape: np.ones(shape)

In [ ]:
ones(3)

array([1., 1., 1.])

In [ ]:
ones(3, 3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ones(3, 3, 3)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

**np methods**

In [ ]:
arr = np.array([[1, 2],
                [32, 16],
                [1, 5]])

In [ ]:
arr.shape

(3, 2)

In [ ]:
arr.max(axis=1)

array([ 2, 32,  5])

In [ ]:
arr.max(axis=0)

array([32, 16])

In [ ]:
A = np.arange(1, 11).reshape(5,2)
B = np.linspace(10, 30, 10).reshape(5,2)

In [ ]:
A

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# as we can see linspace is just a method of forming sorted array with same step
# from arg1(2) to arg2(3) with arg3(5) shape
np.linspace(2, 3, 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
B

array([[10.        , 12.22222222],
       [14.44444444, 16.66666667],
       [18.88888889, 21.11111111],
       [23.33333333, 25.55555556],
       [27.77777778, 30.        ]])

# **Ladies and Gentlemen:** <br>
# **Typical python coder by "Microsoft Bing Image creator"'s opinion:** <br>

<img src='https://th.bing.com/th/id/OIG.sWQJU9ZUTkKSiaURgNCG?pid=ImgGn' width=50%>

<img src='https://th.bing.com/th/id/OIG.fmbdwbM6_KXa0fH3T1jv?pid=ImgGn' width=50%>

<img src='https://th.bing.com/th/id/OIG._HNgSHl2lY2cJK1mzcwC?pid=ImgGn' width=50%>


<img src='https://th.bing.com/th/id/OIG.BX3IIIDMyadPkKi8_rA1?pid=ImgGn&w=1024&h=1024&rs=1' width=50%>

# **I AGREE**