In [81]:
import tensorflow as tf

In [82]:
# tensors are similar to lists
tensor_indx = tf.constant([1, 2, 3, 4, 5])
print(tensor_indx[0])
print(tensor_indx[1:4+1])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [83]:
tensor_indx_2d = tf.constant(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

In [84]:
# getting the 1st elem of 0th arr in matrix
print(tensor_indx_2d[0, 1])

tf.Tensor(2, shape=(), dtype=int32)


In [85]:
# slice example
print(tensor_indx_2d[0, 1:2+1])

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [86]:
print(tensor_indx_2d[:, 0])

tf.Tensor([1 4 7], shape=(3,), dtype=int32)


In [87]:
# 2d matricies have the following structure of indecies:
# [rows, cols]
# in this case [1, 2] means 2nd elem from 1st row
# EZ? EZ!

In [88]:
tensor_3d = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3],
    dtype=tf.float32
)

In [89]:
print(tensor_3d)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(3, 5, 5), dtype=float32)


In [90]:
print(tensor_3d[0, 2, 2])

tf.Tensor(1.0, shape=(), dtype=float32)


In [91]:
# 3d tensors have the following index formula:

# [dim, row, column]
# in this case tensor[1, 2, 3] means that we want
# to access 3rd column of 2nd row of 1st dimension

In [92]:
# EZ?
# EZ!

In [93]:
print(tensor_3d[:, :, 0])

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]], shape=(3, 5), dtype=float32)


In [94]:
tensor_3d.shape

TensorShape([3, 5, 5])

<img src='https://i.ibb.co/RQSkr9C/image.png' width=80%>

In [95]:
to_abs_tensor = tf.constant([-5])
print(tf.abs(to_abs_tensor))

tf.Tensor([5], shape=(1,), dtype=int32)


In [96]:
# VERY EZ

In [97]:
to_sqrt_tensor = tf.constant([[49], [64]], dtype=tf.float32)
print(tf.sqrt(to_sqrt_tensor))

tf.Tensor(
[[7.]
 [8.]], shape=(2, 1), dtype=float32)


In [98]:
to_sqrt_tensor = tf.constant([49], dtype=tf.float32)
print(tf.sqrt(to_sqrt_tensor))

tf.Tensor([7.], shape=(1,), dtype=float32)


In [99]:
to_sqrt_tensor = tf.constant([-4], dtype=tf.float32)
print(tf.sqrt(to_sqrt_tensor))

tf.Tensor([nan], shape=(1,), dtype=float32)


In [100]:
tensor_1 = tf.constant([6, 5, 4])
tensor_2 = tf.constant([3, 2, 1])

print(tensor_1 / tensor_2)

tf.Tensor([2.  2.5 4. ], shape=(3,), dtype=float64)


In [101]:
# or harder:

print(tf.divide(tensor_1, tensor_2))

tf.Tensor([2.  2.5 4. ], shape=(3,), dtype=float64)


In [102]:
# but in case of 0:

tensor_2 = tf.constant([3, 2, 0])

In [103]:
print(tensor_1 / tensor_2)

tf.Tensor([2.  2.5 inf], shape=(3,), dtype=float64)


In [104]:
# 0 division results inf

In [105]:
print(tf.divide(tensor_1, tensor_2))

tf.Tensor([2.  2.5 inf], shape=(3,), dtype=float64)


In [106]:
print(tf.math.divide_no_nan(tensor_1, tensor_2))

tf.Tensor([2.  2.5 0. ], shape=(3,), dtype=float64)


In [ ]:
# via divide_no_nan zero division results 0.
# Mathematicians got angry

In [ ]:
tensor_1 = tf.constant([5, 3, 6, 6, 4, 6])
tensor_2 = tf.con