In [1]:
import tensorflow as tf

In [2]:
# in tf we can also make tensors of powers like:
x = tf.constant([[1, 2, 3], [3, 4, 5]])
y = tf.constant([[2, 2, 2], [2, 2, 2]])

In [3]:
print(tf.math.pow(x, y))

tf.Tensor(
[[ 1  4  9]
 [ 9 16 25]], shape=(2, 3), dtype=int32)


In [7]:
tensor_2d_ez = tf.constant([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [10]:
print(tf.math.reduce_sum(tensor_2d_ez, axis=0))
print(tf.math.reduce_sum(tensor_2d_ez, axis=1))
print(tf.math.reduce_sum(tensor_2d_ez, axis=None))

tf.Tensor([15 18 21 24], shape=(4,), dtype=int32)
tf.Tensor([10 26 42], shape=(3,), dtype=int32)
tf.Tensor(78, shape=(), dtype=int32)


In [11]:
print(tf.math.reduce_max(tensor_2d_ez, axis=0))
print(tf.math.reduce_max(tensor_2d_ez, axis=1))
print(tf.math.reduce_max(tensor_2d_ez, axis=None))

tf.Tensor([ 9 10 11 12], shape=(4,), dtype=int32)
tf.Tensor([ 4  8 12], shape=(3,), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)


In [12]:
print(tf.math.reduce_min(tensor_2d_ez, axis=0))
print(tf.math.reduce_min(tensor_2d_ez, axis=1))
print(tf.math.reduce_min(tensor_2d_ez, axis=None))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 5 9], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [13]:
tensor_3d = tf.constant([
    [[1, 2, 3], [1, 2, 3]],
    [[4, 5, 6], [4, 5, 6]],
    [[7, 8, 9], [7, 8, 9]]
])

In [14]:
print(tensor_3d.shape)

(3, 2, 3)


In [18]:
print(tf.math.reduce_max(tensor_3d, axis=0))
print(tf.math.reduce_max(tensor_3d, axis=1))
print(tf.math.reduce_max(tensor_3d, axis=None))
# working with many dimensions we have more than only axis 1 or 0
print(tf.math.reduce_max(tensor_3d, axis=2))

tf.Tensor(
[[7 8 9]
 [7 8 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(
[[3 3]
 [6 6]
 [9 9]], shape=(3, 2), dtype=int32)


In [20]:
tensor_2d_ez = tf.constant([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
], dtype=tf.float32)

In [21]:
print(tf.math.reduce_mean(tensor_2d_ez, axis=0))
print(tf.math.reduce_mean(tensor_2d_ez, axis=1))
print(tf.math.reduce_mean(tensor_2d_ez, axis=None))

tf.Tensor([5. 6. 7. 8.], shape=(4,), dtype=float32)
tf.Tensor([ 2.5  6.5 10.5], shape=(3,), dtype=float32)
tf.Tensor(6.5, shape=(), dtype=float32)


In [ ]:
# top_k returns us k max elems and their indecies

In [23]:
print(tf.math.top_k(tensor_2d_ez, k=1))

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[ 4.],
       [ 8.],
       [12.]], dtype=float32)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[3],
       [3],
       [3]])>)


In [24]:
print(tf.math.top_k(tensor_2d_ez, k=2))

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 4.,  3.],
       [ 8.,  7.],
       [12., 11.]], dtype=float32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [3, 2],
       [3, 2]])>)


**LINEAR ALGEBRA IN TF**
(tf sounds like team fortress)

In [27]:
x_1 = tf.constant([
    [1, 2, 3],
    [1, 2, 3]
])

x_2 = tf.constant([
    [1, 2],
    [1, 2],
    [1, 2]
])

In [28]:
tf.linalg.matmul(x_1, x_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 12],
       [ 6, 12]])>

<img src='https://www.statlect.com/images/matrix-algebra-multiplication.png' width=50%>

In [30]:
x_1 = tf.constant([
    [1, 2, 3],
    [1, 2, 3]
])

x_2 = tf.constant([
    [1, 2, 3]
])

print(tf.linalg.matmul(x_1, x_2, transpose_b=True))

tf.Tensor(
[[14]
 [14]], shape=(2, 1), dtype=int32)


In [31]:
# we also have such a cool detail:

In [35]:
print(x_1 @ tf.transpose(x_2))

tf.Tensor(
[[14]
 [14]], shape=(2, 1), dtype=int32)


In [36]:
# * is a symbol of normal multiplication
# while @ is a sign of matrix multiplication from linear algebra

In [37]:
tensor_3d = tf.constant([
    [[1, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 2, 3]]
])


tensor2_3d = tf.constant([
    [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
])

In [38]:
print(tensor_3d @ tensor2_3d)

tf.Tensor(
[[[ 6 12 18]
  [ 6 12 18]]

 [[ 6 12 18]
  [ 6 12 18]]

 [[ 6 12 18]
  [ 6 12 18]]], shape=(3, 2, 3), dtype=int32)
