In [1]:
import tensorflow as tf

# **SPARSE TENSORS**

In [2]:
tensor_sparse = tf.sparse.SparseTensor(
    indices=[[1, 1], [3, 4]], values=[11, 55], dense_shape=[5, 6]
)

In [3]:
sparsed = tf.sparse.to_dense(tensor_sparse)
print(sparsed)

tf.Tensor(
[[ 0  0  0  0  0  0]
 [ 0 11  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 55  0]
 [ 0  0  0  0  0  0]], shape=(5, 6), dtype=int32)


In [4]:
# sparsed tensor is tensor of dense_shape shape
# filled with 0s excepting custom values on special indecies

# **STRING TENSORS**

In [5]:
tensor_string = tf.constant(['hello', 'world', '!'])
print(tensor_string)

tf.Tensor([b'hello' b'world' b'!'], shape=(3,), dtype=string)


In [6]:
print(tf.strings.join(['Hello', 'Fellow', 'Kids'], separator=' '))

tf.Tensor(b'Hello Fellow Kids', shape=(), dtype=string)


In [7]:
print(tf.strings.length(['All', 'we had to do', 'was follow', 'the damn train', 'Cj']))

tf.Tensor([ 3 12 10 14  2], shape=(5,), dtype=int32)


# **VARIABLES**

In [8]:
x = tf.constant([1, 2])

In [9]:
x_var = tf.Variable(x, name='var1')

In [10]:
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [11]:
x = tf.Variable(0)
x.assign(1)
print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>


In [12]:
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [13]:
# assigning new var value with substracting arg from original value
x_var.assign_sub([1, 1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 1], dtype=int32)>

In [14]:
# the same explanation is for
x_var.assign_add([5, 6])
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>


In [15]:
# damn...
# Tutorial says that we are gonna be using GPU now...
# And I'm in vscode and have an Amd card
# And kinda lazy to watch these GPU setup tutorials...
# See ya in CoLab.

In [16]:
# Two hours later: (meme from sponge bob ya know)
# ok. Now I'm in colab

In [19]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [30]:
with tf.device('/device:GPU:0'):
  x_tens = tf.constant([1, 2, 3], dtype=float)


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [32]:
x_tens.device

'/job:localhost/replica:0/task:0/device:GPU:0'

# 🍾🍾🍾🎉🎉🎉
# **WOOOOOOOO!**
# **I finished basics module**
# **We start building neural networks with TensorFlow since Now**