In [1]:
import tensorflow as tf

In [2]:
x_argmax = tf.constant([
    [2, 20, 30, 3, 6],
    [5, 6, 7, 8, 300],
    [0, 90, 4, 2, 11]
])

In [3]:
print(x_argmax.shape)

(3, 5)


In [5]:
print(tf.math.argmax(x_argmax[0]))

tf.Tensor(2, shape=(), dtype=int64)


**WTF?! 2 is maximum? rly? No... 2 is the index of maximum element, that is 30**

In [6]:
print(tf.math.argmax(tf.constant([100, 2, 3, 4, 5, 6])))

tf.Tensor(0, shape=(), dtype=int64)


In [11]:
print(tf.math.argmax(x_argmax))

tf.Tensor([1 2 0 1 1], shape=(5,), dtype=int64)


THE SAME THING IS ABOUT argmin

In [12]:
print(tf.argmin(x_argmax[0]))

tf.Tensor(0, shape=(), dtype=int64)


But with multi dimensional tensors we have to specify axis:

In [14]:
print(x_argmax)

tf.Tensor(
[[  2  20  30   3   6]
 [  5   6   7   8 300]
 [  0  90   4   2  11]], shape=(3, 5), dtype=int32)


In [15]:
# it returns rows indicies with highest value
print(tf.argmax(x_argmax, axis=0))
# the maximum val of 0th column is in the 1st row (it's 5)
# then in the 1st column it's in the 2nd row(last) (it's 20)
# and in the 2nd column it's in the 0th row(first) (it's 30)
# and so on

tf.Tensor([1 2 0 1 1], shape=(5,), dtype=int64)


In [17]:
# here it returns us number of column with the highest value for a row
print(tf.argmax(x_argmax, axis=1))

tf.Tensor([2 4 1], shape=(3,), dtype=int64)
